;;;; checkpoint.lisp
;;;;
;;;; Persistence for Raven-LLM: save a trained model to a single binary
;;;; file, load it back later without retraining.
;;;;
;;;; File format v1:
;;;;   4 bytes    magic     "RAVN" (ASCII)
;;;;   1 byte     version   1
;;;;   4 bytes    hlen      header length in bytes (little-endian u32)
;;;;   hlen bytes header    UTF-8 text of a plist:
;;;;                          (:spec <spec-sexp> :vocab-chars "<chars>")
;;;;   4 bytes    n-tensors number of tensor blobs (little-endian u32)
;;;;   for each tensor (in the deterministic order COLLECT-TENSORS gives):
;;;;     1 byte     rank
;;;;     4*rank     dims       (little-endian u32 each)
;;;;     4*N        data       (IEEE-754 single-float, little-endian,
;;;;                             N = product of dims, row-major)
;;;;
;;;; Rationale for storing SPEC + VOCAB-CHARS but NOT :PE table or the
;;;; vocab hash table:
;;;;   - :PE is a fixed sinusoidal function of position, regenerated by
;;;;     BUILD-MODEL-PARAMS from the spec — no need to save it.
;;;;   - The vocab hash table is derivable from the chars vector.
;;;;
;;;; Endianness: little-endian throughout, independent of the host, so
;;;; checkpoints move between machines without surprise.
;;;;
;;;; How to run (from repo root in an SBCL REPL, after loading the rest):
;;;;   (load (compile-file "src/checkpoint.lisp"))
;;;;   (test-checkpoint)   ; roundtrip a trained tiny model
;;;;
;;;; Typical usage:
;;;;   (multiple-value-bind (p s v) (train :corpus-path "..." :steps 5000)
;;;;     (save-checkpoint "runs/poe.ravn" p s v))
;;;;
;;;;   ;; Later, in a fresh SBCL:
;;;;   (multiple-value-bind (p s v) (load-checkpoint "runs/poe.ravn")
;;;;     (format t "~A~%" (generate p s v "The raven " :n-tokens 200)))

(in-package :cl-user)


;;; ------------------------------------------------------------------
;;; Low-level byte-order helpers
;;; ------------------------------------------------------------------
;;;
;;; SBCL's SB-KERNEL:SINGLE-FLOAT-BITS returns a signed 32-bit int with
;;; the IEEE-754 bit pattern; SB-KERNEL:MAKE-SINGLE-FLOAT is the inverse.
;;; LDB works on Lisp integers regardless of sign representation, so we
;;; can extract bytes uniformly.

(defun write-u8 (byte stream)
  (declare (type (unsigned-byte 8) byte))
  (write-byte byte stream))

(defun write-u32-le (n stream)
  (declare (type (unsigned-byte 32) n))
  (write-byte (ldb (byte 8 0)  n) stream)
  (write-byte (ldb (byte 8 8)  n) stream)
  (write-byte (ldb (byte 8 16) n) stream)
  (write-byte (ldb (byte 8 24) n) stream))

(defun read-u8 (stream)
  (read-byte stream))

(defun read-u32-le (stream)
  (let ((b0 (read-byte stream))
        (b1 (read-byte stream))
        (b2 (read-byte stream))
        (b3 (read-byte stream)))
    (logior b0 (ash b1 8) (ash b2 16) (ash b3 24))))

(defun write-f32-le (x stream)
  (declare (type single-float x))
  (let ((bits (sb-kernel:single-float-bits x)))
    (write-byte (ldb (byte 8 0)  bits) stream)
    (write-byte (ldb (byte 8 8)  bits) stream)
    (write-byte (ldb (byte 8 16) bits) stream)
    (write-byte (ldb (byte 8 24) bits) stream)))

(defun read-f32-le (stream)
  (let ((bits (logior (read-byte stream)
                      (ash (read-byte stream) 8)
                      (ash (read-byte stream) 16)
                      (ash (read-byte stream) 24))))
    ;; Convert unsigned 0..2^32-1 to signed for MAKE-SINGLE-FLOAT.
    (when (>= bits (expt 2 31))
      (decf bits (expt 2 32)))
    (sb-kernel:make-single-float bits)))

(defun write-bytes (bytes stream)
  "Write a (simple-array (unsigned-byte 8) (*)) verbatim."
  (write-sequence bytes stream))

(defun read-bytes (n stream)
  "Read N bytes into a fresh (simple-array (unsigned-byte 8) (n))."
  (let ((buf (make-array n :element-type '(unsigned-byte 8))))
    (read-sequence buf stream)
    buf))


;;; ------------------------------------------------------------------
;;; Tensor blob I/O
;;; ------------------------------------------------------------------

(defun write-tensor (tensor stream)
  "Write RANK, DIMS, then row-major single-float data."
  (declare (type tensor tensor))
  (let ((dims (array-dimensions tensor)))
    (write-u8 (length dims) stream)
    (dolist (d dims) (write-u32-le d stream))
    (dotimes (i (array-total-size tensor))
      (write-f32-le (row-major-aref tensor i) stream))))

(defun read-tensor-into! (tensor stream)
  "Read a tensor blob from STREAM into the already-allocated TENSOR.
   Signals an error if the on-disk shape doesn't match TENSOR's shape."
  (declare (type tensor tensor))
  (let* ((rank      (read-u8 stream))
         (file-dims (loop repeat rank collect (read-u32-le stream)))
         (want-dims (array-dimensions tensor)))
    (unless (equal file-dims want-dims)
      (error "read-tensor-into!: shape mismatch — file has ~A, expected ~A"
             file-dims want-dims))
    (dotimes (i (array-total-size tensor))
      (setf (row-major-aref tensor i) (read-f32-le stream)))
    tensor))


;;; ------------------------------------------------------------------
;;; High-level save / load
;;; ------------------------------------------------------------------
;;;
;;; SAVE-CHECKPOINT writes header (spec + vocab chars) followed by the
;;; tensor blobs in the order COLLECT-TENSORS returns them.
;;;
;;; LOAD-CHECKPOINT reads the header, rebuilds the vocab from chars and
;;; the fresh params tree from the spec via BUILD-MODEL-PARAMS, then
;;; walks the fresh tree with COLLECT-TENSORS and fills each tensor
;;; from the file. That works because both save and load side call
;;; COLLECT-TENSORS on structurally-identical trees, and the walk is
;;; deterministic (spec order at the top, then plist order within each
;;; module).

(defparameter +ravn-magic+   #(82 65 86 78)) ; "RAVN"
(defparameter +ravn-version+ 1)

(defun save-checkpoint (path params spec vocab)
  "Serialize PARAMS + SPEC + VOCAB to PATH. Overwrites any existing file."
  (let* ((header-plist (list :spec        spec
                             :vocab-chars (coerce (vocab-chars vocab) 'string)))
         (header-str   (with-standard-io-syntax
                         (let ((*print-readably* t))
                           (prin1-to-string header-plist))))
         (header-bytes (sb-ext:string-to-octets header-str
                                                 :external-format :utf-8))
         (tensors      (collect-tensors params)))
    (with-open-file (s path :direction :output
                             :element-type '(unsigned-byte 8)
                             :if-exists :supersede
                             :if-does-not-exist :create)
      (write-bytes +ravn-magic+ s)
      (write-u8   +ravn-version+ s)
      (write-u32-le (length header-bytes) s)
      (write-bytes header-bytes s)
      (write-u32-le (length tensors) s)
      (dolist (tt tensors)
        (write-tensor tt s)))
    (format t "~&Saved checkpoint to ~A  (~D tensors, header ~D bytes)~%"
            path (length tensors) (length header-bytes))
    path))

(defun load-checkpoint (path)
  "Read a checkpoint from PATH. Returns (values PARAMS SPEC VOCAB).
   Signals an error on magic/version/shape mismatch."
  (with-open-file (s path :direction :input
                           :element-type '(unsigned-byte 8))
    ;; Magic
    (let ((magic (read-bytes 4 s)))
      (unless (equalp magic +ravn-magic+)
        (error "load-checkpoint: bad magic ~A — not a RAVN checkpoint" magic)))
    ;; Version
    (let ((v (read-u8 s)))
      (unless (= v +ravn-version+)
        (error "load-checkpoint: unsupported version ~D (this build handles ~D)"
               v +ravn-version+)))
    ;; Header
    (let* ((hlen         (read-u32-le s))
           (header-bytes (read-bytes hlen s))
           (header-str   (sb-ext:octets-to-string header-bytes
                                                  :external-format :utf-8))
           (header       (with-standard-io-syntax (read-from-string header-str)))
           (spec         (getf header :spec))
           (vocab-chars  (getf header :vocab-chars))
           (vocab        (build-vocab vocab-chars))
           (params       (build-model-params spec)))
      ;; Tensors
      (let* ((n       (read-u32-le s))
             (tensors (collect-tensors params)))
        (unless (= n (length tensors))
          (error "load-checkpoint: tensor count mismatch — file has ~D, spec produces ~D"
                 n (length tensors)))
        (dolist (tt tensors)
          (read-tensor-into! tt s)))
      (format t "~&Loaded checkpoint from ~A~%" path)
      (values params spec vocab))))


;;; ------------------------------------------------------------------
;;; Roundtrip test
;;; ------------------------------------------------------------------
;;;
;;; Train a tiny model, save, load into fresh vars, verify:
;;;   1. Every tensor of the reloaded params equals the original bit-for-bit.
;;;   2. Loss on a fixed sequence is identical before/after save+load
;;;      (proves the reloaded model computes the same thing).
;;;   3. Vocab roundtrips.

(defun test-checkpoint (&key (path "/tmp/raven-test.ravn"))
  (format t "~&=== test-checkpoint: train → save → load → compare ===~%")
  (let* ((text   (with-output-to-string (s)
                   (dotimes (_ 100) (write-string "the raven " s))))
         (vocab  (build-vocab text))
         (v      (vocab-size vocab))
         (corpus (encode vocab text))
         (cfg    (list :vocab-size v :d-model 16 :n-heads 2
                       :n-layers 1 :max-len 16 :d-ff 32 :eps 1.0f-5))
         (spec   (build-gpt-lm-spec cfg))
         (params (build-model-params spec))
         (state  (adam-alloc params))
         (fwd    (make-model-fwd spec))
         (bwd    (make-model-bwd spec)))
    (dotimes (_ 150)
      (multiple-value-bind (input target) (sample-window corpus 16)
        (train-step! fwd bwd params state input target :lr 5.0f-3)))
    ;; Compute reference loss + logits on a fixed input
    (let* ((probe    (subseq corpus 0 16))
           (probe-in (make-array 16 :element-type 'fixnum
                                     :initial-contents (coerce probe 'list)))
           (target   (make-array 16 :element-type 'fixnum
                                     :initial-contents
                                     (coerce (subseq corpus 1 17) 'list)))
           (loss-before (nth-value 0
                                   (softmax-ce-fwd
                                    (nth-value 0 (funcall fwd params probe-in))
                                    target))))
      ;; Save + reload
      (save-checkpoint path params spec vocab)
      (multiple-value-bind (p2 s2 v2) (load-checkpoint path)
        ;; Test 1: bit-exact tensor equality
        (let ((original (collect-tensors params))
              (loaded   (collect-tensors p2))
              (mismatches 0)
              (max-diff 0.0f0))
          (mapc (lambda (a b)
                  (dotimes (i (array-total-size a))
                    (let ((d (abs (- (row-major-aref a i)
                                     (row-major-aref b i)))))
                      (when (> d max-diff) (setf max-diff d))
                      (when (> d 0.0f0) (incf mismatches)))))
                original loaded)
          (format t "  tensor bit-equality: ~D mismatches, max-diff ~,4E  ~A~%"
                  mismatches max-diff
                  (if (zerop mismatches) "PASS" "FAIL")))
        ;; Test 2: loss is identical
        (let* ((fwd2       (make-model-fwd s2))
               (loss-after (nth-value 0
                                      (softmax-ce-fwd
                                       (nth-value 0 (funcall fwd2 p2 probe-in))
                                       target))))
          (format t "  loss before=~,6E  after=~,6E  ~A~%"
                  loss-before loss-after
                  (if (= loss-before loss-after) "PASS" "FAIL")))
        ;; Test 3: vocab roundtrip
        (let ((chars-eq (string= (coerce (vocab-chars vocab) 'string)
                                 (coerce (vocab-chars v2) 'string))))
          (format t "  vocab chars match: ~A~%" (if chars-eq "PASS" "FAIL")))))))
